AUTHOR		= Robin Scheider

# EXTERNAL PROGRAMS:
# = ESSENTIAL PROGRAMS =
# == Basic Shell Utilities ==
ECHO		?= echo
CP		?= cp
CD		?= cd
TAIL		?= tail
TPUT		?= tput
# == LaTeX ==
BIBER		?= biber
PDFLATEX	?= pdflatex
MAKEINDEX	?= makeindex
XINDY		?= xindy
KPSEWHICH	?= kpsewhich
TAILLOG		?= $(TAIL) -n 5
LATEXCLEAN	?= LaTeX-rm-tmpfiles	## Ein kleines Shellskript von mir
PDFOPTMOD	?= pdfoptmod		## Ein kleines Shellskript von mir

UPLOADCONF	?= $(HOME)/.filezilla/ncftp/robin.de.marissa.hostorama.ch
UPLOADCOM	?= ncftpput -m -f $(UPLOADCONF)


TPUTDONE	?= $(TPUT) setaf 2
TPUTRESET	?= $(TPUT) sgr0
