.PHONY: help all clean $(JOBNAME).pdf log main upload echoURL gitdiffs
## Abhängigkeiten nicht Prüfen
.SILENT: help all clean $(JOBNAME).pdf log main upload echoURL gitdiffs gitstats files/git/version.tex
## Befehle nicht vor dem Ausführen anzeigen

%.pdf: %.tex
	$(PDFLATEX) "$<"
	$(TPUTDONE)
	$(ECHO) "$(JOBNAME) done"
	$(TPUTRESET)

log: $(JOBNAME).log
	$(TAILLOG) $(JOBNAME).log
	texloganalyser $(JOBNAME).log

gitstats:
	./.git/hooks/post-commit
	$(TPUTDONE)
	$(ECHO) "gitstats done"
	$(TPUTRESET)

upload:
echoURL:
	$(ECHO) "http://`cat $(UPLOADCONF)|grep "^host"|cut -d " " -f 2`/"$(UPLOADDIR)/$(UPLOADFILE)

clean:
	$(LATEXCLEAN)
