#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use feature qw(say);
use utf8;
use open qw(:std :utf8);
binmode STDOUT, ':encoding(UTF-8)';

$^I = ".bak";

while (<>) { ## Schule|school|letter|scrlttr2
	s{\A%% <(?:Schule|school)/([^<>]+?).tex> (?:Vorlageversion|template version) ([^<> ]+?) <Robin Schneider>}{%% <school/$1.tex> template $2 by Robin `ypid` Schneider <ypid23\@aol.de>\n%% The current version can be found on: https://github.com/ypid/typesetting/blob/master/templates/school/$1.tex}ms;
    s{\A%%%Präambel\Z}{%%% preamble}ms;
    s{\A%\\listfiles.*}{%\\listfiles %% listfiles to logfile}m;
    s{\A%% spet?zifische angaben\Z}{%% specific indications}msi;
    s{\A%%%Body\Z}{%%% body}ms;
    s{\A\\input{/home/rsadmin/Dokumente/LaTeX/input-document/titelpages/Epochenheft}\Z}{\\input{titelpages-EpochenheftRS.tex}}ms;
	# if (/\A#!/) {
	# 	$_ .= "## Copyright (C) 2011 by Yours Truly";
	# }
	# print <STDOUT> "$ARGV";
	print;
}
