#!/bin/bash
## Optimize a text used as LaTeX input (mainly micro typography stuff)
##
## @licence AGPL-3.0-only <https://www.gnu.org/licenses/agpl-3.0.html>
## @author Copyright (C) 2015 Robin Schneider <ypid@riseup.net>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, version 3 of the
## License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

# sed 's/\<ca\./circa/Ig' --in-place *.tex
# \> does not match for dot.
#
# s/\{\\textquotedbl\}([[:space:].)])/}\1/g;
# s/\{\\textquotedbl\}(\w)/\\enquote{\1/g;
# URL regex written quick and dirty for https://github.com/ypid/latex-packages/issues/7
# s@(\<(https?|ftp)://[[:alnum:]_./-]+/)([^[:alnum:]]|[.])@\\url{\1}\2@ig;
# s@(\<(https?|ftp)://[[:alnum:]_./-]+(/[[:alnum:]]+)+)@\\url{\1}@ig;
sed --regexp-extended '
s@\<(https://creativecommons.org/compatiblelicenses|https://creativecommons.org/)@\\url{\1}@ig;
s/\<z\.B\./\\zB/Ig;
s/\<ca\./circa/Ig;
s/\<bzw./beziehungsweise/Ig;
s/\<d\.h\./das heißt/Ig;
' --in-place ./*.tex
# ' latex-optimize-text-test-input
