#!/bin/bash
# Post-{commit,checkout,merge}
#
LaTeX-git-commit-count > files/git/version.tex ## \readgitstat{7}
LaTeX-git-log --width=14 > files/git/versions-log.tex
# LaTeX-gitstats >/dev/null
#LaTeX-gitstats.sh "" >/dev/null
git fsck --full
